ZF\OAuth2\Document\Client:
  type: document
  fields:
    id:
      id: true
      type: integer
    clientId:
      type: string
    secret:
      type: string
    redirectUri:
      type: string
    grantType:
      type: string
  indexes:
    clientId_idx:
      keys:
        clientId:
          order: asc
      options:
  referenceMany:
    accessToken:
      targetDocument: ZF\OAuth2\Document\AccessToken
      mappedBy: client
    authorizationCode:
      targetDocument: ZF\OAuth2\Document\AuthorizationCode
      mappedBy: client
    refreshToken:
      targetDocument: ZF\OAuth2\Document\RefreshToken
      mappedBy: client
    jwt:
      targetDocument: ZF\OAuth2\Document\Jwt
      mappedBy: client
    publicKey:
      targetDocument: ZF\OAuth2\Document\PublicKey
      mappedBy: client
    jti:
      targetDocument: ZF\OAuth2\Document\Jti
      mappedBy: client
