ZF\OAuth2\Document\RefreshToken:
  type: document
  fields:
    id:
      id: true
      type: integer
    refreshToken:
      type: string
    expires:
      type: date
  referenceOne:
    client:
      targetDocument: ZF\OAuth2\Document\Client
      inversedBy: refreshToken
